server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      # 开启网管的 动态路由，服务发现定位,便可以从 Eureka获取实际路由地址
      discovery:
        locator:
          enabled: true
      routes:
        - id: payment_routh    #路由的ID，没有固定规则但要求唯一，建议配合服务名
          # uri: http://localhost:8001   #匹配后的路由地址，静态路由
          uri: lb://CLOUD-PAYMENT-SERVICE  #带LB的动态路由，LB协议
          predicates:
            - Path=/payment/get/**
            # 访问 http://localhost:9527/payment/get/7，通过断言匹配本路由

        - id: payment_routh2
          uri: lb://CLOUD-PAYMENT-SERVICE
          predicates:
            - Path=/payment/lb/**   #断言,路径相匹配的进行路由


eureka:
  instance:
    hostname: cloud-gateway-service
    prefer-ip-address: true
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka


# 本模块只是网关，管理路由，没有其他用故没有业务类

# 一般用的都是 动态路由， 路由URI协议为 LB，表示启用gateway的负载均衡
# URI写成这样， URI: lb://CLOUD-PAYMENT-SERVICE,
# 匹配到本路由 会根据服务名找到 all服务提供者,然后根据LB找到实际提供者