server:
  port: 80
spring:
  application:
    name: cloud-consumer-hystrix-order80

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
        defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    prefer-ip-address: true
    instance-id: cloud-consumer-hystrix-order80

# Hystrix 服务熔断和降级一般用在 服务调用端

# HystrixCommand 的优先级大于 FeignHystrix
# 开启了 Feign服务调用 的服务熔断降级
feign:
  hystrix:
    enabled: true


# 注意feign的超时时间仍要设置大于 HystrixProperties中的超时时间，
# 不然由于feign的超时会导致 fallback的执行
ribbon:
  # 建立连接后从发送请求到接受回复的最大时间
  ReadTimeout:  5000
  # OpenFeign和远程微服务建立http连接的最大耗费时间
  ConnectTimeout: 5000


# 超时时间配置，此处全局超时配置时间大于@HystrixProperty配置时间后，
# @HystrixProperty注解中的超时才生效,
# 当yml文件的超时时间改成小于@HystrixProperty设置的时间, 则生效的是yml文件中设置的时间2秒.
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000


# 客户端不同于服务端，服务端开启的时断路器，不需要配置全局 超时时间
# 而客户端是使能疣猪哥，搭配feign使用，开启feign的 hystrix功能